### ISSUE TITLE
Custom `GenesisBlockBuilder`

### ISSUE THREAD

**Issue by JoshOrndorff** [Off-Narrative-Labs/Tuxedo#107]
Related to my question on the [Substrate Stack Exchange: Extrinsics in Genesis Block](https://substrate.stackexchange.com/questions/10105/extrinsics-in-genesis-block).

Substrate chains by default do not have any extrinsics in the genesis block. This is fine in many cases, but we desire to have extrinsics in the genesis block. The most concrete use case I have in mind is putting a timestamp there. That would allow us to remove the first block hack introduced in #100. It would also be useful for initial token distributions and other usecases as explained in the stack exchange question.

To achieve this we need to implement the [`GeneisBlockBuilder` trait](https://paritytech.github.io/polkadot-sdk/master/sc_chain_spec/trait.BuildGenesisBlock.html). The defacto standard implementation in Substrate chains is the [`GenesisBlockBuilder` struct](https://paritytech.github.io/polkadot-sdk/master/sc_chain_spec/struct.GenesisBlockBuilder.html) and I propose we take inspiration from it but just add some genesis extrinsics.

Just braindumping, the implementatin might look something like this?

```rust
/// A Genesis block builder similar to the default in sc_chain_spec, but this one
/// allows extrinsics in the genesis block
pub struct TuxedoGenesisBlockBuilder {
  // Fields TBD
}

// Inspired by https://paritytech.github.io/polkadot-sdk/master/src/sc_chain_spec/genesis.rs.html#124
impl<Block: BlockT, B: Backend<Block>, E: RuntimeVersionOf> BuildGenesisBlock<Block>
	for TuxedoGenesisBlockBuilder<Block, B, E>
{
	type BlockImportOperation = <B as Backend<Block>>::BlockImportOperation;

	fn build_genesis_block(self) -> sp_blockchain::Result<(Block, Self::BlockImportOperation)> {
		let Self { genesis_pre_state, genesis_extrinsics, commit_genesis_state, backend, executor, _phantom } = self;

		let genesis_state_version = resolve_state_version_from_wasm(&genesis_storage, &executor)?;
		let mut op = backend.begin_operation()?;
		let mut genesis_block = construct_genesis_block::<Block>(state_root, genesis_state_version);

		// TODO push extrinsics to block
		// TODO calculate the new post-state. Maybe we can actually 
		// execute the transactions somehow; that would be ideal
		// Or maybe we can just manually construct the correct output state.

		let state_root =
			op.set_genesis_state(genesis_storage, commit_genesis_state, genesis_state_version)?;

		Ok((genesis_block, op))
	}
}
```

Perhaps we could also clean up the in-runtime aspects of the broader genesis by only allowing extrinsics to create state. Like when you fill in the genesis config in the chain spec, you actually just fill in some json like this.

```
genesis: {
  code: ...,
  timestamp: ...,
  genesis_extrinsics: [Mint(100, Alice), Mint(50, Bob)]
}
```

**Comment by muraca** [comment]
The consequences of this on #100 were bugging me, so I spent quite some time this morning trying to figure this out.
I was initially trying to use BlockBuilder to build a real block, but looks like this might not be possible, since the Client needed for BlockBuilder is created after the GenesisBlockBuilder. 
Later I'll try to implement a custom one from scratch, based on the default in `sc_chain_spec`

**Comment by JoshOrndorff** [comment]
That's right; you need the genesis block to create the client. Implementing the `GenesisBlockBuilder` is needed here.

And the way to wire it into the node template is to use the [`new_full_parts_with_genesis_builder` function](https://paritytech.github.io/polkadot-sdk/master/sc_service/fn.new_full_parts_with_genesis_builder.html) instead of the simpler `new_full_parts` that we [currently use](https://github.com/Off-Narrative-Labs/Tuxedo/blob/6ae548e40ddf7e1390a36d2a76a48b9e632e875d/node/src/service.rs#L75-L80).
