### ISSUE TITLE
Wallet cannot sync blocks with Transactions

### ISSUE THREAD

**Issue by JoshOrndorff** [Off-Narrative-Labs/Tuxedo#120]
At some point the wallet broke on main. Most likely when we did one of the dependency updates like #95 for example.

I fixed part of the issue in #119 but there is still a bigger problem. This is the underlying issue that is making the CI fail on #100 we just don't see it on `main` because there are no transactions in most block on `main`.

To reproduce on `main`:
```sh
# Run the node in one terminal
./target/release/node-template --dev

# Sync the wallet a few times and notice that it works fine when blocks are empty.
./target/release/tuxedo-template-wallet show-balance
./target/release/tuxedo-template-wallet show-balance

# Send a transaction that goes through successfully on chain
./target/release/tuxedo-template-wallet spend-coins -o 90

# Try to sync the wallet again, but now it fails to sync past the block that contains a transaction.
./target/release/tuxedo-template-wallet show-balance
```

@muraca did some debugging and got this output, although I wasn't 100% sure how.

![image](https://github.com/Off-Narrative-Labs/Tuxedo/assets/2915325/836fa4cd-63c1-44c5-81a1-f0f76a7a638c)

**Comment by muraca** [comment]
fixed in #121
