### ISSUE TITLE
Wallet: Add command to clear all data

### ISSUE THREAD

**Issue by muraca** [Off-Narrative-Labs/Tuxedo#133]
I'm lazy and I use the wallet in tests without specifying a custom data path. 
I need to manually go to my platform-specific folder and delete manually each time I need to restart the chain.
I think we should ad a command to clear all wallet data.
It should either have a long name, so people can't run it by mistake, or be conditionally compiled, if we only want to keep it for testing purposes.

**Comment by JoshOrndorff** [comment]
Agreed. And a similar feature I thought of is to add a `--tmp` flag to the wallet just like the node has so that it can start with a clean data directory for _this run_ only without clobbering any data you already had saved.

**Comment by muraca** [comment]
Wow, the `--tmp` flag (or `--dev`, mirroring the node's flag) is a much better idea for my use case, thanks

**Comment by JoshOrndorff** [comment]
We could have both flags just like the node:

```
      --dev
          Specify the development chain. This flag sets `--chain=dev`, `--force-authoring`, `--rpc-cors=all`, `--alice`, and `--tmp` flags, unless explicitly overridden
--tmp
          Run a temporary node. A temporary directory will be created to store the configuration and will be deleted at the end of the process. Note: the directory is random per process execution. This directory is used as base path which includes: database, node key and keystore. When `--dev` is given and no explicit `--base-path`, this option is implied
```

In the wallet's case there isn't as much to do.

```
--dev
          Specify a temporary development wallet instance. It will contain the development key and use a temporary directory (like --tmp)

--tmp
          A temporary directory will be created to store the configuration and will be deleted at the end of the process.
```
