### ISSUE TITLE
Proposal to Integrate Mint Coin Functionality into the Wallet

### ISSUE THREAD

**Issue by NadigerAmit** [Off-Narrative-Labs/Tuxedo#163]
Hi @JoshOrndorff 
cc: @AltiMario

This is Amit from Mlabs.

I want to raise a proposal regarding integrating the "mint coin" functionality into the current wallet system. 
While the existing Money piece supports Mint, the functionality is not currently available in the wallet.

Given the educational purpose of the current wallet, I believe it would be beneficial to include support for minting coins. 
This addition could enhance the wallet's utility and provide users with a more comprehensive experience.

Here is a suggested implementation:

**1. Minting Coins for Default Account (e.g., SHAWN):**

**Command:** ./target/release/tuxedo-template-wallet mint-coins 200
This command would mint coins for the default account (SHAWN in this case) with the specified amount (200).

**2. Minting Coins Based on the Public Key of the Owner:**

**Command:**  ./target/release/tuxedo-template-wallet mint-coins-based-on-public-key-of-owner --amount 900 --owner publicKeyOfUser
This command would allow minting coins for a specific account identified by its public key, with the specified amount (900).

If we prefer not to expose the mint coin functionality to users directly, an alternative use case could be considered:

Considering the wallet's capability to manage multiple key pairs (supported through generate-key and insert-key functionalities), we could automatically provide a default number of coins to every user when a new key is inserted into the wallet. 
For instance, 100 coins could be allocated as a default for each user, either upon key insertion or upon user request. These coins would serve testing purposes, such as purchasing virtual items like a "kitty."

I am eager to hear your thoughts on this proposal and whether you believe it aligns with our goals for the wallet's functionality and user experience.

Thank you for considering this suggestion. I look forward to discussing it further.

BR,
Amit
MLabs

**Comment by JoshOrndorff** [comment]
I think it's wise to add minting functionality. Good idea.

I like a CLI similar to what you proposed. Lets add a single new `mint-coins` subcommand. It has an optional amount argument (default is 100 or something) and an optional receiver address (default is to pull one randomly from the wallet).

**Comment by NadigerAmit** [comment]
Thanks @JoshOrndorff, let me make change and create the pull request for the same,
