### ISSUE TITLE
Efficient UTXO Search for Users in Tuxedo Blockchain

### ISSUE THREAD

**Issue by NadigerAmit** [Off-Narrative-Labs/Tuxedo#184]
I am currently exploring optimal methods for searching UTXOs belonging to other users within the wallet of the Tuxedo blockchain. Specifically, I am interested in identifying UTXOs associated with certain criteria, such as kitties listed for sale in the context of our application.

One potential approach I am considering involves scanning all blocks, transactions, and UTXOs during the synchronization operation. This would allow us to filter and store UTXOs belonging to each user (identified by their public key) in the local database. Subsequently, we could retrieve relevant UTXOs based on specific criteria, such as kitties listed for sale, when needed.

While this method provides a straightforward solution, one concern is the potential increase in the size of the local database on each wallet.

Alternatively, another option could involve utilizing dedicated storage solutions like IPFS (InterPlanetary File System) to store all UTXOs. This would enable efficient querying without directly impacting the local wallet databases.

Considering the current landscape of Tuxedo, I am leaning towards the initial approach of storing UTXOs in the local database of each wallet. However, I am open to discussing other potential strategies or innovative solutions that align with the capabilities of Tuxedo.

I would greatly appreciate your insights and expertise on this matter. Your guidance will be instrumental in ensuring the efficiency and scalability of our approach to UTXO search within the Tuxedo blockchain.

**Comment by JoshOrndorff** [comment]
Both of the techniques you described are useful and precidented. Building this feature in the wallet is the best place to start especially for your kitties dApp.

Your observation that the local DB will be larger if it stores kitty data is correct. Not all users should store that data. Only users that care about kitties should store it. And even then, they should only store their own kitties. Currently the wallet identifies which utxos are relevant to the user by filtering based on verifier and constraint checker. the constraint checker logic is hard coded and will need to be improved. I recommend making it similar to the verifier filter system and maybe combining them into one.

https://github.com/Off-Narrative-Labs/Tuxedo/blob/1ad23430126711d6fca8899e4f00306e76bf98f8/wallet/src/main.rs#L72-L79

https://github.com/Off-Narrative-Labs/Tuxedo/blob/1ad23430126711d6fca8899e4f00306e76bf98f8/wallet/src/sync.rs#L265-L273

The other idea of storing all the data in a secondary place like ipfs or an sql database is also a good idea. This is the job of an indexer. If you plan to make some kind of kitty marketplace that shows all kitties that are currently for sale, you would want something like this to back it.
