### ISSUE TITLE
Multisig

### ISSUE THREAD

**Issue by JoshOrndorff** [Off-Narrative-Labs/Tuxedo#26]
For milestone 2 of the [original grant proposal](https://github.com/w3f/Grants-Program/blob/master/applications/tuxedo.md#milestone-2--wallet-and-multisig) we need to implement a multisig wallet. As described in Section 2 of the [EUTXO paper](https://jmchapman.io/papers/eutxo.pdf) there are two ways to do a multisig, and I propose we **implement both**.

**`Verifier`-Based Approach**

The simple way is to create a `Varifier` implementation that is similar to `SigCheck` but requires a certain number of valid signatures rather than just a single one. This kind of multi-sig has been around since bitcoin. It is also somewhat inconvenient for users because it requires aggregating all of the signatures through off-chain communication between the signatories.

```rust
/// A Threshold multisignature. Some number of member signatories collectively own inputs
/// guarded by this verifier. A valid redeemer must supply valid signatures by at least
/// `threshold` of the signatories. If the threshold is greater than the number of signatories
/// the input can never be consumed.
struct ThresholdMultiSignature {
  /// The minimum number of valid signatures needed to consume this input
  threshold: u8,
  /// All the member signatories, some (or all depending on the threshold) of whom must
  /// produce signatures over the transaction that will consume this input.
  signatories: Vec<H256>,
}
```

**`ConstraintChecker`-Based Approach**

The second way, as outlined in EUTXO, is to allow aggregating the signatures on-chain in a smart contract like way. This would be implemented as a `ConstraintChecker`. A signatory makes a proposal by consuming the original multisig and creating a new one with all the same data plus their proposal plus their own signature. Then other signatories would consume that utxo and replace it with one with all the same data plus their own signature. And eventually the final signatory would consume the utxo and replace it with just the proposal.

**Comment by coax1d** [comment]
#50
