### ISSUE TITLE
Eliminate dependency on `frame-metadata`

### ISSUE THREAD

**Issue by JoshOrndorff** [Off-Narrative-Labs/Tuxedo#87]
Followup to https://github.com/Off-Narrative-Labs/Tuxedo/issues/82

Now that https://github.com/paritytech/substrate/pull/14398 landed in Substrate, we should be able to remove `frame-metadata`, the last frame-specific logic from our dependency tree.

This is a pretty small change, we just need to do the corresponding Substrate update (probably next monthly release) and we will magically get the smaller dependency graph.

**Comment by muraca** [comment]
@JoshOrndorff up for visibility 😄

**Comment by JoshOrndorff** [comment]
Solved in #86
